interface Ascii {
  dec: string;
  oct: string;
  hex: string;
  bin: string;
  symbol: string;
  html_num: string;
  html_name: string;
  description: string;
}

interface AsciiGroup {
  type: string;
  name: string;
  table: Ascii[];
}

export type { Ascii, AsciiGroup };

export const asciiTable: AsciiGroup[] = [
  {
    type: "control_character",
    name: "Control Characters",
    table: [
      {
        dec: "0",
        oct: "0",
        hex: "0",
        bin: "0",
        symbol: "NUL",
        html_num: "&#00;",
        html_name: "",
        description: "Null character",
      },
      {
        dec: "1",
        oct: "1",
        hex: "1",
        bin: "1",
        symbol: "SOH",
        html_num: "&#01;",
        html_name: "",
        description: "Start of Heading",
      },
      {
        dec: "2",
        oct: "2",
        hex: "2",
        bin: "10",
        symbol: "STX",
        html_num: "&#02;",
        html_name: "",
        description: "Start of Text",
      },
      {
        dec: "3",
        oct: "3",
        hex: "3",
        bin: "11",
        symbol: "ETX",
        html_num: "&#03;",
        html_name: "",
        description: "End of Text",
      },
      {
        dec: "4",
        oct: "4",
        hex: "4",
        bin: "100",
        symbol: "EOT",
        html_num: "&#04;",
        html_name: "",
        description: "End of Transmission",
      },
      {
        dec: "5",
        oct: "5",
        hex: "5",
        bin: "101",
        symbol: "ENQ",
        html_num: "&#05;",
        html_name: "",
        description: "Enquiry",
      },
      {
        dec: "6",
        oct: "6",
        hex: "6",
        bin: "110",
        symbol: "ACK",
        html_num: "&#06;",
        html_name: "",
        description: "Acknowledge",
      },
      {
        dec: "7",
        oct: "7",
        hex: "7",
        bin: "111",
        symbol: "BEL",
        html_num: "&#07;",
        html_name: "",
        description: "Bell, Alert",
      },
      {
        dec: "8",
        oct: "10",
        hex: "8",
        bin: "1000",
        symbol: "BS",
        html_num: "&#08;",
        html_name: "",
        description: "Backspace",
      },
      {
        dec: "9",
        oct: "11",
        hex: "9",
        bin: "1001",
        symbol: "HT",
        html_num: "&#09;",
        html_name: "",
        description: "Horizontal Tab",
      },
      {
        dec: "10",
        oct: "12",
        hex: "0A",
        bin: "1010",
        symbol: "LF",
        html_num: "&#10;",
        html_name: "",
        description: "Line Feed",
      },
      {
        dec: "11",
        oct: "13",
        hex: "0B",
        bin: "1011",
        symbol: "VT",
        html_num: "&#11;",
        html_name: "",
        description: "Vertical Tabulation",
      },
      {
        dec: "12",
        oct: "14",
        hex: "0C",
        bin: "1100",
        symbol: "FF",
        html_num: "&#12;",
        html_name: "",
        description: "Form Feed",
      },
      {
        dec: "13",
        oct: "15",
        hex: "0D",
        bin: "1101",
        symbol: "CR",
        html_num: "&#13;",
        html_name: "",
        description: "Carriage Return",
      },
      {
        dec: "14",
        oct: "16",
        hex: "0E",
        bin: "1110",
        symbol: "SO",
        html_num: "&#14;",
        html_name: "",
        description: "Shift Out",
      },
      {
        dec: "15",
        oct: "17",
        hex: "0F",
        bin: "1111",
        symbol: "SI",
        html_num: "&#15;",
        html_name: "",
        description: "Shift In",
      },
      {
        dec: "16",
        oct: "20",
        hex: "10",
        bin: "10000",
        symbol: "DLE",
        html_num: "&#16;",
        html_name: "",
        description: "Data Link Escape",
      },
      {
        dec: "17",
        oct: "21",
        hex: "11",
        bin: "10001",
        symbol: "DC1",
        html_num: "&#17;",
        html_name: "",
        description: "Device Control One (XON)",
      },
      {
        dec: "18",
        oct: "22",
        hex: "12",
        bin: "10010",
        symbol: "DC2",
        html_num: "&#18;",
        html_name: "",
        description: "Device Control Two",
      },
      {
        dec: "19",
        oct: "23",
        hex: "13",
        bin: "10011",
        symbol: "DC3",
        html_num: "&#19;",
        html_name: "",
        description: "Device Control Three (XOFF)",
      },
      {
        dec: "20",
        oct: "24",
        hex: "14",
        bin: "10100",
        symbol: "DC4",
        html_num: "&#20;",
        html_name: "",
        description: "Device Control Four",
      },
      {
        dec: "21",
        oct: "25",
        hex: "15",
        bin: "10101",
        symbol: "NAK",
        html_num: "&#21;",
        html_name: "",
        description: "Negative Acknowledge",
      },
      {
        dec: "22",
        oct: "26",
        hex: "16",
        bin: "10110",
        symbol: "SYN",
        html_num: "&#22;",
        html_name: "",
        description: "Synchronous Idle",
      },
      {
        dec: "23",
        oct: "27",
        hex: "17",
        bin: "10111",
        symbol: "ETB",
        html_num: "&#23;",
        html_name: "",
        description: "End of Transmission Block",
      },
      {
        dec: "24",
        oct: "30",
        hex: "18",
        bin: "11000",
        symbol: "CAN",
        html_num: "&#24;",
        html_name: "",
        description: "Cancel",
      },
      {
        dec: "25",
        oct: "31",
        hex: "19",
        bin: "11001",
        symbol: "EM",
        html_num: "&#25;",
        html_name: "",
        description: "End of medium",
      },
      {
        dec: "26",
        oct: "32",
        hex: "1A",
        bin: "11010",
        symbol: "SUB",
        html_num: "&#26;",
        html_name: "",
        description: "Substitute",
      },
      {
        dec: "27",
        oct: "33",
        hex: "1B",
        bin: "11011",
        symbol: "ESC",
        html_num: "&#27;",
        html_name: "",
        description: "Escape",
      },
      {
        dec: "28",
        oct: "34",
        hex: "1C",
        bin: "11100",
        symbol: "FS",
        html_num: "&#28;",
        html_name: "",
        description: "File Separator",
      },
      {
        dec: "29",
        oct: "35",
        hex: "1D",
        bin: "11101",
        symbol: "GS",
        html_num: "&#29;",
        html_name: "",
        description: "Group Separator",
      },
      {
        dec: "30",
        oct: "36",
        hex: "1E",
        bin: "11110",
        symbol: "RS",
        html_num: "&#30;",
        html_name: "",
        description: "Record Separator",
      },
      {
        dec: "31",
        oct: "37",
        hex: "1F",
        bin: "11111",
        symbol: "US",
        html_num: "&#31;",
        html_name: "",
        description: "Unit Separator",
      },
    ],
  },
  {
    type: "symbol",
    name: "Symbols",
    table: [
      {
        dec: "32",
        oct: "40",
        hex: "20",
        bin: "100000",
        symbol: "SP",
        html_num: "&#32;",
        html_name: "",
        description: "Space",
      },
      {
        dec: "33",
        oct: "41",
        hex: "21",
        bin: "100001",
        symbol: "!",
        html_num: "&#33;",
        html_name: "&excl;",
        description: "Exclamation mark",
      },
      {
        dec: "34",
        oct: "42",
        hex: "22",
        bin: "100010",
        symbol: '"',
        html_num: "&#34;",
        html_name: "&quot;",
        description: "Double quotes (or speech marks)",
      },
      {
        dec: "35",
        oct: "43",
        hex: "23",
        bin: "100011",
        symbol: "#",
        html_num: "&#35;",
        html_name: "&num;",
        description: "Number sign",
      },
      {
        dec: "36",
        oct: "44",
        hex: "24",
        bin: "100100",
        symbol: "$",
        html_num: "&#36;",
        html_name: "&dollar;",
        description: "Dollar",
      },
      {
        dec: "37",
        oct: "45",
        hex: "25",
        bin: "100101",
        symbol: "%",
        html_num: "&#37;",
        html_name: "&percnt;",
        description: "Per cent sign",
      },
      {
        dec: "38",
        oct: "46",
        hex: "26",
        bin: "100110",
        symbol: "&",
        html_num: "&#38;",
        html_name: "&amp;",
        description: "Ampersand",
      },
      {
        dec: "39",
        oct: "47",
        hex: "27",
        bin: "100111",
        symbol: "'",
        html_num: "&#39;",
        html_name: "&apos;",
        description: "Single quote",
      },
      {
        dec: "40",
        oct: "50",
        hex: "28",
        bin: "101000",
        symbol: "(",
        html_num: "&#40;",
        html_name: "&lparen;",
        description: "Open parenthesis (or open bracket)",
      },
      {
        dec: "41",
        oct: "51",
        hex: "29",
        bin: "101001",
        symbol: ")",
        html_num: "&#41;",
        html_name: "&rparen;",
        description: "Close parenthesis (or close bracket)",
      },
      {
        dec: "42",
        oct: "52",
        hex: "2A",
        bin: "101010",
        symbol: "*",
        html_num: "&#42;",
        html_name: "&ast;",
        description: "Asterisk",
      },
      {
        dec: "43",
        oct: "53",
        hex: "2B",
        bin: "101011",
        symbol: "+",
        html_num: "&#43;",
        html_name: "&plus;",
        description: "Plus",
      },
      {
        dec: "44",
        oct: "54",
        hex: "2C",
        bin: "101100",
        symbol: ",",
        html_num: "&#44;",
        html_name: "&comma;",
        description: "Comma",
      },
      {
        dec: "45",
        oct: "55",
        hex: "2D",
        bin: "101101",
        symbol: "-",
        html_num: "&#45;",
        html_name: "",
        description: "Hyphen-minus",
      },
      {
        dec: "46",
        oct: "56",
        hex: "2E",
        bin: "101110",
        symbol: ".",
        html_num: "&#46;",
        html_name: "&period;",
        description: "Period, dot or full stop",
      },
      {
        dec: "47",
        oct: "57",
        hex: "2F",
        bin: "101111",
        symbol: "/",
        html_num: "&#47;",
        html_name: "&sol;",
        description: "Slash or divide",
      },
      {
        dec: "58",
        oct: "72",
        hex: "3A",
        bin: "111010",
        symbol: ":",
        html_num: "&#58;",
        html_name: "&colon;",
        description: "Colon",
      },
      {
        dec: "59",
        oct: "73",
        hex: "3B",
        bin: "111011",
        symbol: ";",
        html_num: "&#59;",
        html_name: "&semi;",
        description: "Semicolon",
      },
      {
        dec: "60",
        oct: "74",
        hex: "3C",
        bin: "111100",
        symbol: "<",
        html_num: "&#60;",
        html_name: "&lt;",
        description: "Less than (or open angled bracket)",
      },
      {
        dec: "61",
        oct: "75",
        hex: "3D",
        bin: "111101",
        symbol: "=",
        html_num: "&#61;",
        html_name: "&equals;",
        description: "Equals",
      },
      {
        dec: "62",
        oct: "76",
        hex: "3E",
        bin: "111110",
        symbol: ">",
        html_num: "&#62;",
        html_name: "&gt;",
        description: "Greater than (or close angled bracket)",
      },
      {
        dec: "63",
        oct: "77",
        hex: "3F",
        bin: "111111",
        symbol: "?",
        html_num: "&#63;",
        html_name: "&quest;",
        description: "Question mark",
      },
      {
        dec: "64",
        oct: "100",
        hex: "40",
        bin: "1000000",
        symbol: "@",
        html_num: "&#64;",
        html_name: "&commat;",
        description: "At sign",
      },
      {
        dec: "91",
        oct: "133",
        hex: "5B",
        bin: "1011011",
        symbol: "[",
        html_num: "&#91;",
        html_name: "&lsqb;",
        description: "Opening bracket",
      },
      {
        dec: "92",
        oct: "134",
        hex: "5C",
        bin: "1011100",
        symbol: "\\",
        html_num: "&#92;",
        html_name: "&bsol;",
        description: "Backslash",
      },
      {
        dec: "93",
        oct: "135",
        hex: "5D",
        bin: "1011101",
        symbol: "]",
        html_num: "&#93;",
        html_name: "&rsqb;",
        description: "Closing bracket",
      },
      {
        dec: "94",
        oct: "136",
        hex: "5E",
        bin: "1011110",
        symbol: "^",
        html_num: "&#94;",
        html_name: "&Hat;",
        description: "Caret - circumflex",
      },
      {
        dec: "95",
        oct: "137",
        hex: "5F",
        bin: "1011111",
        symbol: "_",
        html_num: "&#95;",
        html_name: "&lowbar;",
        description: "Underscore",
      },
      {
        dec: "96",
        oct: "140",
        hex: "60",
        bin: "1100000",
        symbol: "`",
        html_num: "&#96;",
        html_name: "&grave;",
        description: "Grave accent",
      },
      {
        dec: "123",
        oct: "173",
        hex: "7B",
        bin: "1111011",
        symbol: "{",
        html_num: "&#123;",
        html_name: "&lcub;",
        description: "Opening brace",
      },
      {
        dec: "124",
        oct: "174",
        hex: "7C",
        bin: "1111100",
        symbol: "|",
        html_num: "&#124;",
        html_name: "&verbar;",
        description: "Vertical bar",
      },
      {
        dec: "125",
        oct: "175",
        hex: "7D",
        bin: "1111101",
        symbol: "}",
        html_num: "&#125;",
        html_name: "&rcub;",
        description: "Closing brace",
      },
      {
        dec: "126",
        oct: "176",
        hex: "7E",
        bin: "1111110",
        symbol: "~",
        html_num: "&#126;",
        html_name: "&tilde;",
        description: "Equivalency sign - tilde",
      },
      {
        dec: "127",
        oct: "177",
        hex: "7F",
        bin: "1111111",
        symbol: "DEL",
        html_num: "&#127;",
        html_name: "",
        description: "Delete",
      },
    ],
  },
  {
    type: "number",
    name: "Numbers",
    table: [
      {
        dec: "48",
        oct: "60",
        hex: "30",
        bin: "110000",
        symbol: "0",
        html_num: "&#48;",
        html_name: "",
        description: "Zero",
      },
      {
        dec: "49",
        oct: "61",
        hex: "31",
        bin: "110001",
        symbol: "1",
        html_num: "&#49;",
        html_name: "",
        description: "One",
      },
      {
        dec: "50",
        oct: "62",
        hex: "32",
        bin: "110010",
        symbol: "2",
        html_num: "&#50;",
        html_name: "",
        description: "Two",
      },
      {
        dec: "51",
        oct: "63",
        hex: "33",
        bin: "110011",
        symbol: "3",
        html_num: "&#51;",
        html_name: "",
        description: "Three",
      },
      {
        dec: "52",
        oct: "64",
        hex: "34",
        bin: "110100",
        symbol: "4",
        html_num: "&#52;",
        html_name: "",
        description: "Four",
      },
      {
        dec: "53",
        oct: "65",
        hex: "35",
        bin: "110101",
        symbol: "5",
        html_num: "&#53;",
        html_name: "",
        description: "Five",
      },
      {
        dec: "54",
        oct: "66",
        hex: "36",
        bin: "110110",
        symbol: "6",
        html_num: "&#54;",
        html_name: "",
        description: "Six",
      },
      {
        dec: "55",
        oct: "67",
        hex: "37",
        bin: "110111",
        symbol: "7",
        html_num: "&#55;",
        html_name: "",
        description: "Seven",
      },
      {
        dec: "56",
        oct: "70",
        hex: "38",
        bin: "111000",
        symbol: "8",
        html_num: "&#56;",
        html_name: "",
        description: "Eight",
      },
      {
        dec: "57",
        oct: "71",
        hex: "39",
        bin: "111001",
        symbol: "9",
        html_num: "&#57;",
        html_name: "",
        description: "Nine",
      },
    ],
  },
  {
    type: "alphabet",
    name: "Alphabet",
    table: [
      {
        dec: "65",
        oct: "101",
        hex: "41",
        bin: "1000001",
        symbol: "A",
        html_num: "&#65;",
        html_name: "",
        description: "Uppercase A",
      },
      {
        dec: "66",
        oct: "102",
        hex: "42",
        bin: "1000010",
        symbol: "B",
        html_num: "&#66;",
        html_name: "",
        description: "Uppercase B",
      },
      {
        dec: "67",
        oct: "103",
        hex: "43",
        bin: "1000011",
        symbol: "C",
        html_num: "&#67;",
        html_name: "",
        description: "Uppercase C",
      },
      {
        dec: "68",
        oct: "104",
        hex: "44",
        bin: "1000100",
        symbol: "D",
        html_num: "&#68;",
        html_name: "",
        description: "Uppercase D",
      },
      {
        dec: "69",
        oct: "105",
        hex: "45",
        bin: "1000101",
        symbol: "E",
        html_num: "&#69;",
        html_name: "",
        description: "Uppercase E",
      },
      {
        dec: "70",
        oct: "106",
        hex: "46",
        bin: "1000110",
        symbol: "F",
        html_num: "&#70;",
        html_name: "",
        description: "Uppercase F",
      },
      {
        dec: "71",
        oct: "107",
        hex: "47",
        bin: "1000111",
        symbol: "G",
        html_num: "&#71;",
        html_name: "",
        description: "Uppercase G",
      },
      {
        dec: "72",
        oct: "110",
        hex: "48",
        bin: "1001000",
        symbol: "H",
        html_num: "&#72;",
        html_name: "",
        description: "Uppercase H",
      },
      {
        dec: "73",
        oct: "111",
        hex: "49",
        bin: "1001001",
        symbol: "I",
        html_num: "&#73;",
        html_name: "",
        description: "Uppercase I",
      },
      {
        dec: "74",
        oct: "112",
        hex: "4A",
        bin: "1001010",
        symbol: "J",
        html_num: "&#74;",
        html_name: "",
        description: "Uppercase J",
      },
      {
        dec: "75",
        oct: "113",
        hex: "4B",
        bin: "1001011",
        symbol: "K",
        html_num: "&#75;",
        html_name: "",
        description: "Uppercase K",
      },
      {
        dec: "76",
        oct: "114",
        hex: "4C",
        bin: "1001100",
        symbol: "L",
        html_num: "&#76;",
        html_name: "",
        description: "Uppercase L",
      },
      {
        dec: "77",
        oct: "115",
        hex: "4D",
        bin: "1001101",
        symbol: "M",
        html_num: "&#77;",
        html_name: "",
        description: "Uppercase M",
      },
      {
        dec: "78",
        oct: "116",
        hex: "4E",
        bin: "1001110",
        symbol: "N",
        html_num: "&#78;",
        html_name: "",
        description: "Uppercase N",
      },
      {
        dec: "79",
        oct: "117",
        hex: "4F",
        bin: "1001111",
        symbol: "O",
        html_num: "&#79;",
        html_name: "",
        description: "Uppercase O",
      },
      {
        dec: "80",
        oct: "120",
        hex: "50",
        bin: "1010000",
        symbol: "P",
        html_num: "&#80;",
        html_name: "",
        description: "Uppercase P",
      },
      {
        dec: "81",
        oct: "121",
        hex: "51",
        bin: "1010001",
        symbol: "Q",
        html_num: "&#81;",
        html_name: "",
        description: "Uppercase Q",
      },
      {
        dec: "82",
        oct: "122",
        hex: "52",
        bin: "1010010",
        symbol: "R",
        html_num: "&#82;",
        html_name: "",
        description: "Uppercase R",
      },
      {
        dec: "83",
        oct: "123",
        hex: "53",
        bin: "1010011",
        symbol: "S",
        html_num: "&#83;",
        html_name: "",
        description: "Uppercase S",
      },
      {
        dec: "84",
        oct: "124",
        hex: "54",
        bin: "1010100",
        symbol: "T",
        html_num: "&#84;",
        html_name: "",
        description: "Uppercase T",
      },
      {
        dec: "85",
        oct: "125",
        hex: "55",
        bin: "1010101",
        symbol: "U",
        html_num: "&#85;",
        html_name: "",
        description: "Uppercase U",
      },
      {
        dec: "86",
        oct: "126",
        hex: "56",
        bin: "1010110",
        symbol: "V",
        html_num: "&#86;",
        html_name: "",
        description: "Uppercase V",
      },
      {
        dec: "87",
        oct: "127",
        hex: "57",
        bin: "1010111",
        symbol: "W",
        html_num: "&#87;",
        html_name: "",
        description: "Uppercase W",
      },
      {
        dec: "88",
        oct: "130",
        hex: "58",
        bin: "1011000",
        symbol: "X",
        html_num: "&#88;",
        html_name: "",
        description: "Uppercase X",
      },
      {
        dec: "89",
        oct: "131",
        hex: "59",
        bin: "1011001",
        symbol: "Y",
        html_num: "&#89;",
        html_name: "",
        description: "Uppercase Y",
      },
      {
        dec: "90",
        oct: "132",
        hex: "5A",
        bin: "1011010",
        symbol: "Z",
        html_num: "&#90;",
        html_name: "",
        description: "Uppercase Z",
      },
    ],
  },
  {
    type: "alphabet",
    name: "Alphabet",
    table: [
      {
        dec: "97",
        oct: "141",
        hex: "61",
        bin: "1100001",
        symbol: "a",
        html_num: "&#97;",
        html_name: "",
        description: "Lowercase a",
      },
      {
        dec: "98",
        oct: "142",
        hex: "62",
        bin: "1100010",
        symbol: "b",
        html_num: "&#98;",
        html_name: "",
        description: "Lowercase b",
      },
      {
        dec: "99",
        oct: "143",
        hex: "63",
        bin: "1100011",
        symbol: "c",
        html_num: "&#99;",
        html_name: "",
        description: "Lowercase c",
      },
      {
        dec: "100",
        oct: "144",
        hex: "64",
        bin: "1100100",
        symbol: "d",
        html_num: "&#100;",
        html_name: "",
        description: "Lowercase d",
      },
      {
        dec: "101",
        oct: "145",
        hex: "65",
        bin: "1100101",
        symbol: "e",
        html_num: "&#101;",
        html_name: "",
        description: "Lowercase e",
      },
      {
        dec: "102",
        oct: "146",
        hex: "66",
        bin: "1100110",
        symbol: "f",
        html_num: "&#102;",
        html_name: "",
        description: "Lowercase f",
      },
      {
        dec: "103",
        oct: "147",
        hex: "67",
        bin: "1100111",
        symbol: "g",
        html_num: "&#103;",
        html_name: "",
        description: "Lowercase g",
      },
      {
        dec: "104",
        oct: "150",
        hex: "68",
        bin: "1101000",
        symbol: "h",
        html_num: "&#104;",
        html_name: "",
        description: "Lowercase h",
      },
      {
        dec: "105",
        oct: "151",
        hex: "69",
        bin: "1101001",
        symbol: "i",
        html_num: "&#105;",
        html_name: "",
        description: "Lowercase i",
      },
      {
        dec: "106",
        oct: "152",
        hex: "6A",
        bin: "1101010",
        symbol: "j",
        html_num: "&#106;",
        html_name: "",
        description: "Lowercase j",
      },
      {
        dec: "107",
        oct: "153",
        hex: "6B",
        bin: "1101011",
        symbol: "k",
        html_num: "&#107;",
        html_name: "",
        description: "Lowercase k",
      },
      {
        dec: "108",
        oct: "154",
        hex: "6C",
        bin: "1101100",
        symbol: "l",
        html_num: "&#108;",
        html_name: "",
        description: "Lowercase l",
      },
      {
        dec: "109",
        oct: "155",
        hex: "6D",
        bin: "1101101",
        symbol: "m",
        html_num: "&#109;",
        html_name: "",
        description: "Lowercase m",
      },
      {
        dec: "110",
        oct: "156",
        hex: "6E",
        bin: "1101110",
        symbol: "n",
        html_num: "&#110;",
        html_name: "",
        description: "Lowercase n",
      },
      {
        dec: "111",
        oct: "157",
        hex: "6F",
        bin: "1101111",
        symbol: "o",
        html_num: "&#111;",
        html_name: "",
        description: "Lowercase o",
      },
      {
        dec: "112",
        oct: "160",
        hex: "70",
        bin: "1110000",
        symbol: "p",
        html_num: "&#112;",
        html_name: "",
        description: "Lowercase p",
      },
      {
        dec: "113",
        oct: "161",
        hex: "71",
        bin: "1110001",
        symbol: "q",
        html_num: "&#113;",
        html_name: "",
        description: "Lowercase q",
      },
      {
        dec: "114",
        oct: "162",
        hex: "72",
        bin: "1110010",
        symbol: "r",
        html_num: "&#114;",
        html_name: "",
        description: "Lowercase r",
      },
      {
        dec: "115",
        oct: "163",
        hex: "73",
        bin: "1110011",
        symbol: "s",
        html_num: "&#115;",
        html_name: "",
        description: "Lowercase s",
      },
      {
        dec: "116",
        oct: "164",
        hex: "74",
        bin: "1110100",
        symbol: "t",
        html_num: "&#116;",
        html_name: "",
        description: "Lowercase t",
      },
      {
        dec: "117",
        oct: "165",
        hex: "75",
        bin: "1110101",
        symbol: "u",
        html_num: "&#117;",
        html_name: "",
        description: "Lowercase u",
      },
      {
        dec: "118",
        oct: "166",
        hex: "76",
        bin: "1110110",
        symbol: "v",
        html_num: "&#118;",
        html_name: "",
        description: "Lowercase v",
      },
      {
        dec: "119",
        oct: "167",
        hex: "77",
        bin: "1110111",
        symbol: "w",
        html_num: "&#119;",
        html_name: "",
        description: "Lowercase w",
      },
      {
        dec: "120",
        oct: "170",
        hex: "78",
        bin: "1111000",
        symbol: "x",
        html_num: "&#120;",
        html_name: "",
        description: "Lowercase x",
      },
      {
        dec: "121",
        oct: "171",
        hex: "79",
        bin: "1111001",
        symbol: "y",
        html_num: "&#121;",
        html_name: "",
        description: "Lowercase y",
      },
      {
        dec: "122",
        oct: "172",
        hex: "7A",
        bin: "1111010",
        symbol: "z",
        html_num: "&#122;",
        html_name: "",
        description: "Lowercase z",
      },
    ],
  },
  {
    type: "extended_ascii",
    name: "Extended ASCII",
    table: [
      {
        dec: "128",
        oct: "200",
        hex: "80",
        bin: "10000000",
        symbol: "€",
        html_num: "&#8364;",
        html_name: "&euro;",
        description: "Euro sign",
      },
      {
        dec: "129",
        oct: "201",
        hex: "81",
        bin: "10000001",
        symbol: "",
        html_num: "",
        html_name: "",
        description: "Unused",
      },
      {
        dec: "130",
        oct: "202",
        hex: "82",
        bin: "10000010",
        symbol: "‚",
        html_num: "&#130;",
        html_name: "&sbquo;",
        description: "Single low-9 quotation mark",
      },
      {
        dec: "131",
        oct: "203",
        hex: "83",
        bin: "10000011",
        symbol: "ƒ",
        html_num: "&#131;",
        html_name: "&fnof;",
        description: "Latin small letter f with hook",
      },
      {
        dec: "132",
        oct: "204",
        hex: "84",
        bin: "10000100",
        symbol: "„",
        html_num: "&#132;",
        html_name: "&bdquo;",
        description: "Double low-9 quotation mark",
      },
      {
        dec: "133",
        oct: "205",
        hex: "85",
        bin: "10000101",
        symbol: "…",
        html_num: "&#133;",
        html_name: "&hellip;",
        description: "Horizontal ellipsis",
      },
      {
        dec: "134",
        oct: "206",
        hex: "86",
        bin: "10000110",
        symbol: "†",
        html_num: "&#134;",
        html_name: "&dagger;",
        description: "Dagger",
      },
      {
        dec: "135",
        oct: "207",
        hex: "87",
        bin: "10000111",
        symbol: "‡",
        html_num: "&#135;",
        html_name: "&Dagger;",
        description: "Double dagger",
      },
      {
        dec: "136",
        oct: "210",
        hex: "88",
        bin: "10001000",
        symbol: "ˆ",
        html_num: "&#136;",
        html_name: "&circ;",
        description: "Modifier letter circumflex accent",
      },
      {
        dec: "137",
        oct: "211",
        hex: "89",
        bin: "10001001",
        symbol: "‰",
        html_num: "&#137;",
        html_name: "&permil;",
        description: "Per mille sign",
      },
      {
        dec: "138",
        oct: "212",
        hex: "8A",
        bin: "10001010",
        symbol: "Š",
        html_num: "&#138;",
        html_name: "&Scaron;",
        description: "Latin capital letter S with caron",
      },
      {
        dec: "139",
        oct: "213",
        hex: "8B",
        bin: "10001011",
        symbol: "‹",
        html_num: "&#139;",
        html_name: "&lsaquo;",
        description: "Single left-pointing angle quotation",
      },
      {
        dec: "140",
        oct: "214",
        hex: "8C",
        bin: "10001100",
        symbol: "Œ",
        html_num: "&#140;",
        html_name: "&OElig;",
        description: "Latin capital ligature OE",
      },
      {
        dec: "141",
        oct: "215",
        hex: "8D",
        bin: "10001101",
        symbol: "",
        html_num: "",
        html_name: "",
        description: "Unused",
      },
      {
        dec: "142",
        oct: "216",
        hex: "8E",
        bin: "10001110",
        symbol: "Ž",
        html_num: "&#142;",
        html_name: "&Zcaron;",
        description: "Latin capital letter Z with caron",
      },
      {
        dec: "143",
        oct: "217",
        hex: "8F",
        bin: "10001111",
        symbol: "",
        html_num: "",
        html_name: "",
        description: "Unused",
      },
      {
        dec: "144",
        oct: "220",
        hex: "90",
        bin: "10010000",
        symbol: "",
        html_num: "",
        html_name: "",
        description: "Unused",
      },
      {
        dec: "145",
        oct: "221",
        hex: "91",
        bin: "10010001",
        symbol: "‘",
        html_num: "&#145;",
        html_name: "&lsquo;",
        description: "Left single quotation mark",
      },
      {
        dec: "146",
        oct: "222",
        hex: "92",
        bin: "10010010",
        symbol: "’",
        html_num: "&#146;",
        html_name: "&rsquo;",
        description: "Right single quotation mark",
      },
      {
        dec: "147",
        oct: "223",
        hex: "93",
        bin: "10010011",
        symbol: "“",
        html_num: "&#147;",
        html_name: "&ldquo;",
        description: "Left double quotation mark",
      },
      {
        dec: "148",
        oct: "224",
        hex: "94",
        bin: "10010100",
        symbol: "”",
        html_num: "&#148;",
        html_name: "&rdquo;",
        description: "Right double quotation mark",
      },
      {
        dec: "149",
        oct: "225",
        hex: "95",
        bin: "10010101",
        symbol: "•",
        html_num: "&#149;",
        html_name: "&bull;",
        description: "Bullet",
      },
      {
        dec: "150",
        oct: "226",
        hex: "96",
        bin: "10010110",
        symbol: "–",
        html_num: "&#150;",
        html_name: "&ndash;",
        description: "En dash",
      },
      {
        dec: "151",
        oct: "227",
        hex: "97",
        bin: "10010111",
        symbol: "—",
        html_num: "&#151;",
        html_name: "&mdash;",
        description: "Em dash",
      },
      {
        dec: "152",
        oct: "230",
        hex: "98",
        bin: "10011000",
        symbol: "˜",
        html_num: "&#152;",
        html_name: "&tilde;",
        description: "Small tilde",
      },
      {
        dec: "153",
        oct: "231",
        hex: "99",
        bin: "10011001",
        symbol: "™",
        html_num: "&#153;",
        html_name: "&trade;",
        description: "Trade mark sign",
      },
      {
        dec: "154",
        oct: "232",
        hex: "9A",
        bin: "10011010",
        symbol: "š",
        html_num: "&#154;",
        html_name: "&scaron;",
        description: "Latin small letter S with caron",
      },
      {
        dec: "155",
        oct: "233",
        hex: "9B",
        bin: "10011011",
        symbol: "›",
        html_num: "&#155;",
        html_name: "&rsaquo;",
        description: "Single right-pointing angle quotation mark",
      },
      {
        dec: "156",
        oct: "234",
        hex: "9C",
        bin: "10011100",
        symbol: "œ",
        html_num: "&#156;",
        html_name: "&oelig;",
        description: "Latin small ligature oe",
      },
      {
        dec: "157",
        oct: "235",
        hex: "9D",
        bin: "10011101",
        symbol: "",
        html_num: "",
        html_name: "",
        description: "Unused",
      },
      {
        dec: "158",
        oct: "236",
        hex: "9E",
        bin: "10011110",
        symbol: "ž",
        html_num: "&#158;",
        html_name: "&zcaron;",
        description: "Latin small letter z with caron",
      },
      {
        dec: "159",
        oct: "237",
        hex: "9F",
        bin: "10011111",
        symbol: "Ÿ",
        html_num: "&#159;",
        html_name: "&Yuml;",
        description: "Latin capital letter Y with diaeresis",
      },
      {
        dec: "160",
        oct: "240",
        hex: "A0",
        bin: "10100000",
        symbol: "NBSP",
        html_num: "&#160;",
        html_name: "&nbsp;",
        description: "Non-breaking space",
      },
      {
        dec: "161",
        oct: "241",
        hex: "A1",
        bin: "10100001",
        symbol: "¡",
        html_num: "&#161;",
        html_name: "&iexcl;",
        description: "Inverted exclamation mark",
      },
      {
        dec: "162",
        oct: "242",
        hex: "A2",
        bin: "10100010",
        symbol: "¢",
        html_num: "&#162;",
        html_name: "&cent;",
        description: "Cent sign",
      },
      {
        dec: "163",
        oct: "243",
        hex: "A3",
        bin: "10100011",
        symbol: "£",
        html_num: "&#163;",
        html_name: "&pound;",
        description: "Pound sign",
      },
      {
        dec: "164",
        oct: "244",
        hex: "A4",
        bin: "10100100",
        symbol: "¤",
        html_num: "&#164;",
        html_name: "&curren;",
        description: "Currency sign",
      },
      {
        dec: "165",
        oct: "245",
        hex: "A5",
        bin: "10100101",
        symbol: "¥",
        html_num: "&#165;",
        html_name: "&yen;",
        description: "Yen sign",
      },
      {
        dec: "166",
        oct: "246",
        hex: "A6",
        bin: "10100110",
        symbol: "¦",
        html_num: "&#166;",
        html_name: "&brvbar;",
        description: "Pipe, broken vertical bar",
      },
      {
        dec: "167",
        oct: "247",
        hex: "A7",
        bin: "10100111",
        symbol: "§",
        html_num: "&#167;",
        html_name: "&sect;",
        description: "Section sign",
      },
      {
        dec: "168",
        oct: "250",
        hex: "A8",
        bin: "10101000",
        symbol: "¨",
        html_num: "&#168;",
        html_name: "&uml;",
        description: "Spacing diaeresis - umlaut",
      },
      {
        dec: "169",
        oct: "251",
        hex: "A9",
        bin: "10101001",
        symbol: "©",
        html_num: "&#169;",
        html_name: "&copy;",
        description: "Copyright sign",
      },
      {
        dec: "170",
        oct: "252",
        hex: "AA",
        bin: "10101010",
        symbol: "ª",
        html_num: "&#170;",
        html_name: "&ordf;",
        description: "Feminine ordinal indicator",
      },
      {
        dec: "171",
        oct: "253",
        hex: "AB",
        bin: "10101011",
        symbol: "«",
        html_num: "&#171;",
        html_name: "&laquo;",
        description: "Left double angle quotes",
      },
      {
        dec: "172",
        oct: "254",
        hex: "AC",
        bin: "10101100",
        symbol: "¬",
        html_num: "&#172;",
        html_name: "&not;",
        description: "Negation",
      },
      {
        dec: "173",
        oct: "255",
        hex: "AD",
        bin: "10101101",
        symbol: "­SHY",
        html_num: "&#173;",
        html_name: "&shy;",
        description: "Soft hyphen",
      },
      {
        dec: "174",
        oct: "256",
        hex: "AE",
        bin: "10101110",
        symbol: "®",
        html_num: "&#174;",
        html_name: "&reg;",
        description: "Registered trade mark sign",
      },
      {
        dec: "175",
        oct: "257",
        hex: "AF",
        bin: "10101111",
        symbol: "¯",
        html_num: "&#175;",
        html_name: "&macr;",
        description: "Spacing macron - overline",
      },
      {
        dec: "176",
        oct: "260",
        hex: "B0",
        bin: "10110000",
        symbol: "°",
        html_num: "&#176;",
        html_name: "&deg;",
        description: "Degree sign",
      },
      {
        dec: "177",
        oct: "261",
        hex: "B1",
        bin: "10110001",
        symbol: "±",
        html_num: "&#177;",
        html_name: "&plusmn;",
        description: "Plus-or-minus sign",
      },
      {
        dec: "178",
        oct: "262",
        hex: "B2",
        bin: "10110010",
        symbol: "²",
        html_num: "&#178;",
        html_name: "&sup2;",
        description: "Superscript two - squared",
      },
      {
        dec: "179",
        oct: "263",
        hex: "B3",
        bin: "10110011",
        symbol: "³",
        html_num: "&#179;",
        html_name: "&sup3;",
        description: "Superscript three - cubed",
      },
      {
        dec: "180",
        oct: "264",
        hex: "B4",
        bin: "10110100",
        symbol: "´",
        html_num: "&#180;",
        html_name: "&acute;",
        description: "Acute accent - spacing acute",
      },
      {
        dec: "181",
        oct: "265",
        hex: "B5",
        bin: "10110101",
        symbol: "µ",
        html_num: "&#181;",
        html_name: "&micro;",
        description: "Micro sign",
      },
      {
        dec: "182",
        oct: "266",
        hex: "B6",
        bin: "10110110",
        symbol: "¶",
        html_num: "&#182;",
        html_name: "&para;",
        description: "Pilcrow sign - paragraph sign",
      },
      {
        dec: "183",
        oct: "267",
        hex: "B7",
        bin: "10110111",
        symbol: "·",
        html_num: "&#183;",
        html_name: "&middot;",
        description: "Middle dot - Georgian comma",
      },
      {
        dec: "184",
        oct: "270",
        hex: "B8",
        bin: "10111000",
        symbol: "¸",
        html_num: "&#184;",
        html_name: "&cedil;",
        description: "Spacing cedilla",
      },
      {
        dec: "185",
        oct: "271",
        hex: "B9",
        bin: "10111001",
        symbol: "¹",
        html_num: "&#185;",
        html_name: "&sup1;",
        description: "Superscript one",
      },
      {
        dec: "186",
        oct: "272",
        hex: "BA",
        bin: "10111010",
        symbol: "º",
        html_num: "&#186;",
        html_name: "&ordm;",
        description: "Masculine ordinal indicator",
      },
      {
        dec: "187",
        oct: "273",
        hex: "BB",
        bin: "10111011",
        symbol: "»",
        html_num: "&#187;",
        html_name: "&raquo;",
        description: "Right double angle quotes",
      },
      {
        dec: "188",
        oct: "274",
        hex: "BC",
        bin: "10111100",
        symbol: "¼",
        html_num: "&#188;",
        html_name: "&frac14;",
        description: "Fraction one quarter",
      },
      {
        dec: "189",
        oct: "275",
        hex: "BD",
        bin: "10111101",
        symbol: "½",
        html_num: "&#189;",
        html_name: "&frac12;",
        description: "Fraction one half",
      },
      {
        dec: "190",
        oct: "276",
        hex: "BE",
        bin: "10111110",
        symbol: "¾",
        html_num: "&#190;",
        html_name: "&frac34;",
        description: "Fraction three quarters",
      },
      {
        dec: "191",
        oct: "277",
        hex: "BF",
        bin: "10111111",
        symbol: "¿",
        html_num: "&#191;",
        html_name: "&iquest;",
        description: "Inverted question mark",
      },
      {
        dec: "192",
        oct: "300",
        hex: "C0",
        bin: "11000000",
        symbol: "À",
        html_num: "&#192;",
        html_name: "&Agrave;",
        description: "Latin capital letter A with grave",
      },
      {
        dec: "193",
        oct: "301",
        hex: "C1",
        bin: "11000001",
        symbol: "Á",
        html_num: "&#193;",
        html_name: "&Aacute;",
        description: "Latin capital letter A with acute",
      },
      {
        dec: "194",
        oct: "302",
        hex: "C2",
        bin: "11000010",
        symbol: "Â",
        html_num: "&#194;",
        html_name: "&Acirc;",
        description: "Latin capital letter A with circumflex",
      },
      {
        dec: "195",
        oct: "303",
        hex: "C3",
        bin: "11000011",
        symbol: "Ã",
        html_num: "&#195;",
        html_name: "&Atilde;",
        description: "Latin capital letter A with tilde",
      },
      {
        dec: "196",
        oct: "304",
        hex: "C4",
        bin: "11000100",
        symbol: "Ä",
        html_num: "&#196;",
        html_name: "&Auml;",
        description: "Latin capital letter A with diaeresis",
      },
      {
        dec: "197",
        oct: "305",
        hex: "C5",
        bin: "11000101",
        symbol: "Å",
        html_num: "&#197;",
        html_name: "&Aring;",
        description: "Latin capital letter A with ring above",
      },
      {
        dec: "198",
        oct: "306",
        hex: "C6",
        bin: "11000110",
        symbol: "Æ",
        html_num: "&#198;",
        html_name: "&AElig;",
        description: "Latin capital letter AE",
      },
      {
        dec: "199",
        oct: "307",
        hex: "C7",
        bin: "11000111",
        symbol: "Ç",
        html_num: "&#199;",
        html_name: "&Ccedil;",
        description: "Latin capital letter C with cedilla",
      },
      {
        dec: "200",
        oct: "310",
        hex: "C8",
        bin: "11001000",
        symbol: "È",
        html_num: "&#200;",
        html_name: "&Egrave;",
        description: "Latin capital letter E with grave",
      },
      {
        dec: "201",
        oct: "311",
        hex: "C9",
        bin: "11001001",
        symbol: "É",
        html_num: "&#201;",
        html_name: "&Eacute;",
        description: "Latin capital letter E with acute",
      },
      {
        dec: "202",
        oct: "312",
        hex: "CA",
        bin: "11001010",
        symbol: "Ê",
        html_num: "&#202;",
        html_name: "&Ecirc;",
        description: "Latin capital letter E with circumflex",
      },
      {
        dec: "203",
        oct: "313",
        hex: "CB",
        bin: "11001011",
        symbol: "Ë",
        html_num: "&#203;",
        html_name: "&Euml;",
        description: "Latin capital letter E with diaeresis",
      },
      {
        dec: "204",
        oct: "314",
        hex: "CC",
        bin: "11001100",
        symbol: "Ì",
        html_num: "&#204;",
        html_name: "&Igrave;",
        description: "Latin capital letter I with grave",
      },
      {
        dec: "205",
        oct: "315",
        hex: "CD",
        bin: "11001101",
        symbol: "Í",
        html_num: "&#205;",
        html_name: "&Iacute;",
        description: "Latin capital letter I with acute",
      },
      {
        dec: "206",
        oct: "316",
        hex: "CE",
        bin: "11001110",
        symbol: "Î",
        html_num: "&#206;",
        html_name: "&Icirc;",
        description: "Latin capital letter I with circumflex",
      },
      {
        dec: "207",
        oct: "317",
        hex: "CF",
        bin: "11001111",
        symbol: "Ï",
        html_num: "&#207;",
        html_name: "&Iuml;",
        description: "Latin capital letter I with diaeresis",
      },
      {
        dec: "208",
        oct: "320",
        hex: "D0",
        bin: "11010000",
        symbol: "Ð",
        html_num: "&#208;",
        html_name: "&ETH;",
        description: "Latin capital letter ETH",
      },
      {
        dec: "209",
        oct: "321",
        hex: "D1",
        bin: "11010001",
        symbol: "Ñ",
        html_num: "&#209;",
        html_name: "&Ntilde;",
        description: "Latin capital letter N with tilde",
      },
      {
        dec: "210",
        oct: "322",
        hex: "D2",
        bin: "11010010",
        symbol: "Ò",
        html_num: "&#210;",
        html_name: "&Ograve;",
        description: "Latin capital letter O with grave",
      },
      {
        dec: "211",
        oct: "323",
        hex: "D3",
        bin: "11010011",
        symbol: "Ó",
        html_num: "&#211;",
        html_name: "&Oacute;",
        description: "Latin capital letter O with acute",
      },
      {
        dec: "212",
        oct: "324",
        hex: "D4",
        bin: "11010100",
        symbol: "Ô",
        html_num: "&#212;",
        html_name: "&Ocirc;",
        description: "Latin capital letter O with circumflex",
      },
      {
        dec: "213",
        oct: "325",
        hex: "D5",
        bin: "11010101",
        symbol: "Õ",
        html_num: "&#213;",
        html_name: "&Otilde;",
        description: "Latin capital letter O with tilde",
      },
      {
        dec: "214",
        oct: "326",
        hex: "D6",
        bin: "11010110",
        symbol: "Ö",
        html_num: "&#214;",
        html_name: "&Ouml;",
        description: "Latin capital letter O with diaeresis",
      },
      {
        dec: "215",
        oct: "327",
        hex: "D7",
        bin: "11010111",
        symbol: "×",
        html_num: "&#215;",
        html_name: "&times;",
        description: "Multiplication sign",
      },
      {
        dec: "216",
        oct: "330",
        hex: "D8",
        bin: "11011000",
        symbol: "Ø",
        html_num: "&#216;",
        html_name: "&Oslash;",
        description: "Latin capital letter O with slash",
      },
      {
        dec: "217",
        oct: "331",
        hex: "D9",
        bin: "11011001",
        symbol: "Ù",
        html_num: "&#217;",
        html_name: "&Ugrave;",
        description: "Latin capital letter U with grave",
      },
      {
        dec: "218",
        oct: "332",
        hex: "DA",
        bin: "11011010",
        symbol: "Ú",
        html_num: "&#218;",
        html_name: "&Uacute;",
        description: "Latin capital letter U with acute",
      },
      {
        dec: "219",
        oct: "333",
        hex: "DB",
        bin: "11011011",
        symbol: "Û",
        html_num: "&#219;",
        html_name: "&Ucirc;",
        description: "Latin capital letter U with circumflex",
      },
      {
        dec: "220",
        oct: "334",
        hex: "DC",
        bin: "11011100",
        symbol: "Ü",
        html_num: "&#220;",
        html_name: "&Uuml;",
        description: "Latin capital letter U with diaeresis",
      },
      {
        dec: "221",
        oct: "335",
        hex: "DD",
        bin: "11011101",
        symbol: "Ý",
        html_num: "&#221;",
        html_name: "&Yacute;",
        description: "Latin capital letter Y with acute",
      },
      {
        dec: "222",
        oct: "336",
        hex: "DE",
        bin: "11011110",
        symbol: "Þ",
        html_num: "&#222;",
        html_name: "&THORN;",
        description: "Latin capital letter THORN",
      },
      {
        dec: "223",
        oct: "337",
        hex: "DF",
        bin: "11011111",
        symbol: "ß",
        html_num: "&#223;",
        html_name: "&szlig;",
        description: "Latin small letter sharp s - ess-zed",
      },
      {
        dec: "224",
        oct: "340",
        hex: "E0",
        bin: "11100000",
        symbol: "à",
        html_num: "&#224;",
        html_name: "&agrave;",
        description: "Latin small letter a with grave",
      },
      {
        dec: "225",
        oct: "341",
        hex: "E1",
        bin: "11100001",
        symbol: "á",
        html_num: "&#225;",
        html_name: "&aacute;",
        description: "Latin small letter a with acute",
      },
      {
        dec: "226",
        oct: "342",
        hex: "E2",
        bin: "11100010",
        symbol: "â",
        html_num: "&#226;",
        html_name: "&acirc;",
        description: "Latin small letter a with circumflex",
      },
      {
        dec: "227",
        oct: "343",
        hex: "E3",
        bin: "11100011",
        symbol: "ã",
        html_num: "&#227;",
        html_name: "&atilde;",
        description: "Latin small letter a with tilde",
      },
      {
        dec: "228",
        oct: "344",
        hex: "E4",
        bin: "11100100",
        symbol: "ä",
        html_num: "&#228;",
        html_name: "&auml;",
        description: "Latin small letter a with diaeresis",
      },
      {
        dec: "229",
        oct: "345",
        hex: "E5",
        bin: "11100101",
        symbol: "å",
        html_num: "&#229;",
        html_name: "&aring;",
        description: "Latin small letter a with ring above",
      },
      {
        dec: "230",
        oct: "346",
        hex: "E6",
        bin: "11100110",
        symbol: "æ",
        html_num: "&#230;",
        html_name: "&aelig;",
        description: "Latin small letter ae",
      },
      {
        dec: "231",
        oct: "347",
        hex: "E7",
        bin: "11100111",
        symbol: "ç",
        html_num: "&#231;",
        html_name: "&ccedil;",
        description: "Latin small letter c with cedilla",
      },
      {
        dec: "232",
        oct: "350",
        hex: "E8",
        bin: "11101000",
        symbol: "è",
        html_num: "&#232;",
        html_name: "&egrave;",
        description: "Latin small letter e with grave",
      },
      {
        dec: "233",
        oct: "351",
        hex: "E9",
        bin: "11101001",
        symbol: "é",
        html_num: "&#233;",
        html_name: "&eacute;",
        description: "Latin small letter e with acute",
      },
      {
        dec: "234",
        oct: "352",
        hex: "EA",
        bin: "11101010",
        symbol: "ê",
        html_num: "&#234;",
        html_name: "&ecirc;",
        description: "Latin small letter e with circumflex",
      },
      {
        dec: "235",
        oct: "353",
        hex: "EB",
        bin: "11101011",
        symbol: "ë",
        html_num: "&#235;",
        html_name: "&euml;",
        description: "Latin small letter e with diaeresis",
      },
      {
        dec: "236",
        oct: "354",
        hex: "EC",
        bin: "11101100",
        symbol: "ì",
        html_num: "&#236;",
        html_name: "&igrave;",
        description: "Latin small letter i with grave",
      },
      {
        dec: "237",
        oct: "355",
        hex: "ED",
        bin: "11101101",
        symbol: "í",
        html_num: "&#237;",
        html_name: "&iacute;",
        description: "Latin small letter i with acute",
      },
      {
        dec: "238",
        oct: "356",
        hex: "EE",
        bin: "11101110",
        symbol: "î",
        html_num: "&#238;",
        html_name: "&icirc;",
        description: "Latin small letter i with circumflex",
      },
      {
        dec: "239",
        oct: "357",
        hex: "EF",
        bin: "11101111",
        symbol: "ï",
        html_num: "&#239;",
        html_name: "&iuml;",
        description: "Latin small letter i with diaeresis",
      },
      {
        dec: "240",
        oct: "360",
        hex: "F0",
        bin: "11110000",
        symbol: "ð",
        html_num: "&#240;",
        html_name: "&eth;",
        description: "Latin small letter eth",
      },
      {
        dec: "241",
        oct: "361",
        hex: "F1",
        bin: "11110001",
        symbol: "ñ",
        html_num: "&#241;",
        html_name: "&ntilde;",
        description: "Latin small letter n with tilde",
      },
      {
        dec: "242",
        oct: "362",
        hex: "F2",
        bin: "11110010",
        symbol: "ò",
        html_num: "&#242;",
        html_name: "&ograve;",
        description: "Latin small letter o with grave",
      },
      {
        dec: "243",
        oct: "363",
        hex: "F3",
        bin: "11110011",
        symbol: "ó",
        html_num: "&#243;",
        html_name: "&oacute;",
        description: "Latin small letter o with acute",
      },
      {
        dec: "244",
        oct: "364",
        hex: "F4",
        bin: "11110100",
        symbol: "ô",
        html_num: "&#244;",
        html_name: "&ocirc;",
        description: "Latin small letter o with circumflex",
      },
      {
        dec: "245",
        oct: "365",
        hex: "F5",
        bin: "11110101",
        symbol: "õ",
        html_num: "&#245;",
        html_name: "&otilde;",
        description: "Latin small letter o with tilde",
      },
      {
        dec: "246",
        oct: "366",
        hex: "F6",
        bin: "11110110",
        symbol: "ö",
        html_num: "&#246;",
        html_name: "&ouml;",
        description: "Latin small letter o with diaeresis",
      },
      {
        dec: "247",
        oct: "367",
        hex: "F7",
        bin: "11110111",
        symbol: "÷",
        html_num: "&#247;",
        html_name: "&divide;",
        description: "Division sign",
      },
      {
        dec: "248",
        oct: "370",
        hex: "F8",
        bin: "11111000",
        symbol: "ø",
        html_num: "&#248;",
        html_name: "&oslash;",
        description: "Latin small letter o with slash",
      },
      {
        dec: "249",
        oct: "371",
        hex: "F9",
        bin: "11111001",
        symbol: "ù",
        html_num: "&#249;",
        html_name: "&ugrave;",
        description: "Latin small letter u with grave",
      },
      {
        dec: "250",
        oct: "372",
        hex: "FA",
        bin: "11111010",
        symbol: "ú",
        html_num: "&#250;",
        html_name: "&uacute;",
        description: "Latin small letter u with acute",
      },
      {
        dec: "251",
        oct: "373",
        hex: "FB",
        bin: "11111011",
        symbol: "û",
        html_num: "&#251;",
        html_name: "&ucirc;",
        description: "Latin small letter u with circumflex",
      },
      {
        dec: "252",
        oct: "374",
        hex: "FC",
        bin: "11111100",
        symbol: "ü",
        html_num: "&#252;",
        html_name: "&uuml;",
        description: "Latin small letter u with diaeresis",
      },
      {
        dec: "253",
        oct: "375",
        hex: "FD",
        bin: "11111101",
        symbol: "ý",
        html_num: "&#253;",
        html_name: "&yacute;",
        description: "Latin small letter y with acute",
      },
      {
        dec: "254",
        oct: "376",
        hex: "FE",
        bin: "11111110",
        symbol: "þ",
        html_num: "&#254;",
        html_name: "&thorn;",
        description: "Latin small letter thorn",
      },
      {
        dec: "255",
        oct: "377",
        hex: "FF",
        bin: "11111111",
        symbol: "ÿ",
        html_num: "&#255;",
        html_name: "&yuml;",
        description: "Latin small letter y with diaeresis",
      },
    ],
  },
];
